version: "3.3"

services: 
  backend:
    image: tr0els/smarthome-backend:${PROMOTE_BUILD_NUMBER}
    environment:
        EnvironmentName: Production
    ports: 
        - 31001:80
      
  frontend:
    image: tr0els/smarthome-frontend:${PROMOTE_BUILD_NUMBER}
    environment: 
        EnvironmentName: Production
    ports: 
      - 31000:80